#!/bin/sh

cat <<EOF > /etc/config/dockerd
config dockerman 'dockerman'
	option socket_path '/var/run/docker.sock'
	option status_path '/tmp/.docker_action_status'
	option debug 'false'
	option debug_path '/tmp/.docker_debug'
	list ac_allowed_interface 'br-lan'
	option remote_port '2375'
	option remote_endpoint 'false'
EOF